<a href="https://colab.research.google.com/github/sharadgupta27/NumericalPython/blob/main/distribute_lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab 2: Pandas and numpy

In [1]:
import numpy as np
import pandas as pd

## EXERCISE 1: How fast is your car?

Read in automobile data from a CSV file, storing the data in a dataframe `dfcars`.

````` 
Description
The data was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and ten aspects of automobile design and performance for 32 automobiles (1973–74 models).

Format

A data frame with 32 observations on 11 variables.

[, 1]	mpg	     Miles/(US) gallon
[, 2]	cyl	     Number of cylinders
[, 3]	disp	 Displacement (cu.in.)
[, 4]	hp	     Gross horsepower
[, 5]	drat	 Rear axle ratio
[, 6]	wt	     Weight (1000 lbs)
[, 7]	qsec	 1/4 mile time
[, 8]	vs	     V/S
[, 9]	am	     Transmission (0 = automatic, 1 = manual)
[,10]	gear	 Number of forward gears
[,11]	carb	 Number of carburetors
        
Source
Henderson and Velleman (1981), Building multiple regression models interactively. Biometrics, 37, 391–411.
`````

In [2]:
!wget https://raw.githubusercontent.com/sharadgupta27/NumericalPython/main/data/mtcars.csv

--2020-12-20 05:33:45--  https://raw.githubusercontent.com/sharadgupta27/NumericalPython/main/data/mtcars.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1783 (1.7K) [text/plain]
Saving to: ‘mtcars.csv’

mtcars.csv          100%[===================>]   1.74K  --.-KB/s    in 0s      

2020-12-20 05:33:46 (12.8 MB/s) - ‘mtcars.csv’ saved [1783/1783]



In [5]:
# your code here
dfcars = pd.read_csv('mtcars.csv')

In [6]:
dfcars.head(3)

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0      Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1  Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2     Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1

That first column is messed up. Lets fix it.

The first column, which seems to be the name of the car, does not have a name. Here are the first 3 lines of the file:

```
"","mpg","cyl","disp","hp","drat","wt","qsec","vs","am","gear","carb"
"Mazda RX4",21,6,160,110,3.9,2.62,16.46,0,1,4,4
"Mazda RX4 Wag",21,6,160,110,3.9,2.875,17.02,0,1,4,4
```

In [7]:
dfcars = dfcars.rename(columns={"Unnamed: 0": "name"})
dfcars.head()

name   mpg  cyl   disp   hp  ...   qsec  vs  am  gear  carb
0          Mazda RX4  21.0    6  160.0  110  ...  16.46   0   1     4     4
1      Mazda RX4 Wag  21.0    6  160.0  110  ...  17.02   0   1     4     4
2         Datsun 710  22.8    4  108.0   93  ...  18.61   1   1     4     1
3     Hornet 4 Drive  21.4    6  258.0  110  ...  19.44   1   0     3     1
4  Hornet Sportabout  18.7    8  360.0  175  ...  17.02   0   0     3     2

[5 rows x 12 columns]

Columns in a dataframe (series) come with their own types. Some data may be categorical, that is, they come  with only few well defined values. An example is cylinders  (`cyl`). Cars may be 4, 6, or 8 cylindered. There is a ordered interpretation to this  (8 cylinders more powerful engine than 6 cylinders) but also a one-of-three-types interpretation to this. 

Sometimes categorical data does not have an ordered interpretation. An example is `am`: a boolean variable which indicates whether the car is an automatic or not.

Other column types are integer, floating-point, and `object`. The latter is a catch-all for a string or anything Pandas cannot infer, for example, a column that contains data of mixed types. 

Write code to check the datatypes of the columns

In [11]:
# your code here
dfcars.dtypes

name     object
mpg     float64
cyl       int64
disp    float64
hp        int64
drat    float64
wt      float64
qsec    float64
vs        int64
am        int64
gear      int64
carb      int64
dtype: object

Write code to get the unique values of car cylinders

In [12]:
# your code here
dfcars['cyl'].unique()

array([6, 4, 8])

In [13]:
dfcars.cyl.unique()

array([6, 4, 8])

Write code to get the dataframe of the 6 and 8 cylinder cars

In [19]:
# your code here
dfcars[dfcars['cyl'].isin([6,8])]

name   mpg  cyl   disp   hp  ...   qsec  vs  am  gear  carb
0             Mazda RX4  21.0    6  160.0  110  ...  16.46   0   1     4     4
1         Mazda RX4 Wag  21.0    6  160.0  110  ...  17.02   0   1     4     4
3        Hornet 4 Drive  21.4    6  258.0  110  ...  19.44   1   0     3     1
4     Hornet Sportabout  18.7    8  360.0  175  ...  17.02   0   0     3     2
5               Valiant  18.1    6  225.0  105  ...  20.22   1   0     3     1
6            Duster 360  14.3    8  360.0  245  ...  15.84   0   0     3     4
9              Merc 280  19.2    6  167.6  123  ...  18.30   1   0     4     4
10            Merc 280C  17.8    6  167.6  123  ...  18.90   1   0     4     4
11           Merc 450SE  16.4    8  275.8  180  ...  17.40   0   0     3     3
12           Merc 450SL  17.3    8  275.8  180  ...  17.60   0   0     3     3
13          Merc 450SLC  15.2    8  275.8  180  ...  18.00   0   0     3     3
14   Cadillac Fleetwood  10.4    8  472.0  205  ...  17.98   0   0     3     4
15  Lincoln Continental  10.4    8  460.0  215  ...  17.82   0   0     3     4
16    Chrysler Imperial  14.7    8  440.0  230  ...  17.42   0   0     3     4
21     Dodge Challenger  15.5    8  318.0  150  ...  16.87   0   0     3     2
22          AMC Javelin  15.2    8  304.0  150  ...  17.30   0   0     3     2
23           Camaro Z28  13.3    8  350.0  245  ...  15.41   0   0     3     4
24     Pontiac Firebird  19.2    8  400.0  175  ...  17.05   0   0     3     2
28       Ford Pantera L  15.8    8  351.0  264  ...  14.50   0   1     5     4
29         Ferrari Dino  19.7    6  145.0  175  ...  15.50   0   1     5     6
30        Maserati Bora  15.0    8  301.0  335  ...  14.60   0   1     5     8

[21 rows x 12 columns]

Write code to get the dataframe of cars with greter than 30mpg speeds

In [21]:
highspeed = dfcars[dfcars.mpg > 30]

Save the high speed cars in a new csv file in data folder, ie in the file "data/highspeed.csv"

In [22]:
# your code here
highspeed.to_csv('highspeed.csv')

Create a 2-D numpy array from the mpg and wt columns of `dfcars`

In [25]:
# your code here
wt_mpg = np.array(dfcars[['mpg','wt']])
print(wt_mpg)

[[21.     2.62 ]
 [21.     2.875]
 [22.8    2.32 ]
 [21.4    3.215]
 [18.7    3.44 ]
 [18.1    3.46 ]
 [14.3    3.57 ]
 [24.4    3.19 ]
 [22.8    3.15 ]
 [19.2    3.44 ]
 [17.8    3.44 ]
 [16.4    4.07 ]
 [17.3    3.73 ]
 [15.2    3.78 ]
 [10.4    5.25 ]
 [10.4    5.424]
 [14.7    5.345]
 [32.4    2.2  ]
 [30.4    1.615]
 [33.9    1.835]
 [21.5    2.465]
 [15.5    3.52 ]
 [15.2    3.435]
 [13.3    3.84 ]
 [19.2    3.845]
 [27.3    1.935]
 [26.     2.14 ]
 [30.4    1.513]
 [15.8    3.17 ]
 [19.7    2.77 ]
 [15.     3.57 ]
 [21.4    2.78 ]]


In [32]:
cy = dfcars['cyl'].values.T

In [35]:
cy.shape
cy.reshape(-1,1) # same as cy.reshape(32,1)

array([[6],
       [6],
       [4],
       [6],
       [8],
       [6],
       [8],
       [4],
       [4],
       [6],
       [6],
       [8],
       [8],
       [8],
       [8],
       [8],
       [8],
       [4],
       [4],
       [4],
       [4],
       [8],
       [8],
       [8],
       [8],
       [4],
       [4],
       [4],
       [8],
       [6],
       [8],
       [4]])

Reshape this array into a wide style, in other words, transpose it

In [29]:
# your code here
sub = dfcars[['mpg','wt']].values.T
sub.shape

(2, 32)

In [30]:
# your code here
sub.reshape(4,16)

array([[21.   , 21.   , 22.8  , 21.4  , 18.7  , 18.1  , 14.3  , 24.4  ,
        22.8  , 19.2  , 17.8  , 16.4  , 17.3  , 15.2  , 10.4  , 10.4  ],
       [14.7  , 32.4  , 30.4  , 33.9  , 21.5  , 15.5  , 15.2  , 13.3  ,
        19.2  , 27.3  , 26.   , 30.4  , 15.8  , 19.7  , 15.   , 21.4  ],
       [ 2.62 ,  2.875,  2.32 ,  3.215,  3.44 ,  3.46 ,  3.57 ,  3.19 ,
         3.15 ,  3.44 ,  3.44 ,  4.07 ,  3.73 ,  3.78 ,  5.25 ,  5.424],
       [ 5.345,  2.2  ,  1.615,  1.835,  2.465,  3.52 ,  3.435,  3.84 ,
         3.845,  1.935,  2.14 ,  1.513,  3.17 ,  2.77 ,  3.57 ,  2.78 ]])